Online Bookstore Project/src/com/ose/bookstore/model/ejb/BookListDAO.java
/**
 * 
 */
package com.ose.bookstore.model.ejb;

import java.util.ArrayList;
import java.util.List;

import javax.ejb.LocalBean;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import com.ose.bookstore.model.entity.Books;


/**
 * EJB session bean that handles the business logic part of the user details
 * table
 * @author OSE Nepal
 * @version 1.3.0 Oct 4, 2013
 */

/*No-interface view, Stateless Bean*/

@Stateless
@LocalBean
public class BookListDAO {

	@PersistenceContext 
	private EntityManager entityManager; 

	public BookListDAO() {

	}

	/** Searches the table for matching string
	 * @param searchString the string to be searched for
	 * @param category column to be searched for
	 * @return filtered search list
	 */
	public List<Books> search(String searchString, String category) {
		
		CriteriaBuilder cb = entityManager.getCriteriaBuilder();
		CriteriaQuery<Books> query = cb.createQuery(Books.class);
		Root<Books> c = query.from(Books.class);

		query.select(c);
		if (category.equals("all")) {
			List<Predicate> plist = new ArrayList<Predicate>(); 
			plist.add(cb.like(c.<String> get("author"), "%" + searchString + "%"));
			plist.add(cb.like(c.<String> get("title"), "%" + searchString + "%"));
		
			query.select(c);
			query.where(cb.or(plist.toArray(new Predicate[plist.size()])));
		} else {
			query.where(cb.like(c.<String> get(category), "%" + searchString + "%"));
		}
		return entityManager.createQuery(query).getResultList();
	}

	/**
	 * Lists all the books present in the table
	 * 
	 * @return the List containing all the entries in the table
	 */
	public List<Books> getBookList() {

		CriteriaBuilder cb = entityManager.getCriteriaBuilder(); 
		CriteriaQuery<Books> query = cb.createQuery(Books.class); 
		Root<Books> c = query.from(Books.class);
		query.select(c);

		return entityManager.createQuery(query).getResultList();
	}

	/**
	 * A selected by primary key; bookId
	 * 
	 * @param id the unique id to a book
	 * @return the selected book
	 */
	public Books getBook(int id) {
		Books book = new Books();
		book = entityManager.find(Books.class, id);
		return book;
	}

}

Online Bookstore Project/src/com/ose/bookstore/model/entity/ShoppingCart.java
package com.ose.bookstore.model.entity;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Entity implementation class for Entity: ShoppingCart
 * @author OSE Nepal
 * @version 1.3.0 Oct 4, 2013
 */
@Entity
public class ShoppingCart implements Serializable {

	private static final long serialVersionUID = 1L;
	
	// Fields
	@Id
	@GeneratedValue
	private int scId;

	// @ManyToOne
	// private Books books;
	private int userId;

	private int bookId;

	private int bookQuantity;

	// Getters and Setters
	public int getScId() {
		return scId;
	}

	public void setScId(int scId) {
		this.scId = scId;
	}

	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getBookId() {
		return bookId;
	}

	public void setBookId(int bookId) {
		this.bookId = bookId;
	}

	public int getBookQuantity() {
		return bookQuantity;
	}

	public void setBookQuantity(int bookQuantity) {
		this.bookQuantity = bookQuantity;
	}
}

Online Bookstore Project/src/com/ose/bookstore/controller/BooksController.java
/**
 * 
 */
package com.ose.bookstore.controller;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import javax.ejb.EJB;
import javax.enterprise.context.RequestScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.event.RateEvent;

import com.ose.bookstore.model.ejb.BookListDAO;
import com.ose.bookstore.model.ejb.RatingsDAO;
import com.ose.bookstore.model.ejb.ShoppingCartDAO;
import com.ose.bookstore.model.ejb.TempShoppingCartDAO;
import com.ose.bookstore.model.entity.Books;
import com.ose.bookstore.model.entity.Ratings;
import com.ose.bookstore.model.entity.ShoppingCart;

/**
 * Deals with all the page links dispatches present in browsebooks page and
 * bookprofile page
 * @author OSE Nepal
 * @version 1.3.0 Oct 4, 2013
 */
@Named
@RequestScoped
public class BooksController implements Serializable {

	@EJB
	ShoppingCartDAO shoppingCartDao;

	@EJB
	BookListDAO bookListDao;

	@EJB
	RatingsDAO ratingsDao;

	@Inject
	TempShoppingCartDAO tempShoppingCartDao;

	@Inject
	ShoppingCart shoppingCart;

	@Inject
	UserAccountController userAccountController;

	@Inject
	Books currentBook;
	
	@Inject
	Ratings ratings;

	List<ShoppingCart> currentCart;
	
	private static final long serialVersionUID = 1L;

	private Integer rating;/*Average User rating of a book*/

	private int newRating;/*New rating by a user*/

	private int currentId;/*Current Book Id*/

	private int ratingsCount;/*Number of Ratings for a book by different users*/
	
	private Map<Integer, Integer> bookNumber; /*for dropdown menu in bookProfile page*/

	public BooksController() {
	
	}

	/**
	 * Sets the book to be added to the shopping cart in the shoppingCart
	 * instance;
	 *  calls the cartDao function for adding the book for registered users
	 * 	calls tempcartDao function for appending books for unregistered users
	 * 
	 * @return 
	 */
	public String addToShoppingCart() {
		
		if (userAccountController.isFlag()) { 
			shoppingCart.setBookId(currentBook.getBookId());
			shoppingCart.setUserId(userAccountController.getUserDetails()
					.getUserId());
			shoppingCartDao.add(shoppingCart);
		}
		else{
			shoppingCart.setBookId(currentBook.getBookId());
			tempShoppingCartDao.add(shoppingCart);
		}
		
		FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Item(s) added to Cart:", "");
		FacesContext.getCurrentInstance().addMessage(null, message);
		return "";
	}

	/**
	 * Sets the selected book as the current book
	 * 
	 * @param books selected book from the jsf page
	 * @return bookProfile the selected book profile page
	 */
	public String showBookDetails(Books books) {
		this.currentBook = books;
		return "bookProfile?faces-redirect=true";
	}

	/**Sets new Rating of a book for a user
	 * @param rateEvent
	 */
	public void onrate(RateEvent rateEvent) {

		FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO,	"Thank you for your review:", "");
		FacesContext.getCurrentInstance().addMessage(null, message);

		if (!ratingsDao.getUserRating(currentId, userAccountController.getUserDetails().getUserId()).isEmpty()) {
			ratings = ratingsDao.getUserRating(currentId, userAccountController.getUserDetails().getUserId()).get(0);
			ratings.setBookId(currentId);
			ratings.setUserRating5(newRating);
			ratingsDao.setUserRating(ratings);
		} else {
			ratings.setRatingsId(0);
			ratings.setBookId(currentId);
			ratings.setUserRating5(newRating);
			ratings.setUserId(userAccountController.getUserDetails().getUserId());
			ratingsDao.setUserRating(ratings);
		}
	}

	/**The pre-Render function that is loaded before rendering bookProfile page
	 * 
	 */
	public void init() {
		currentBook = bookListDao.getBook(currentId);
		rating = ratingsDao.bookRating(currentId);
		ratingsCount = ratingsDao.getBookRating(currentId).size();
		if (!ratingsDao.getUserRating(currentId, userAccountController.getUserDetails().getUserId()).isEmpty()) {
			ratings = ratingsDao.getUserRating(currentId, userAccountController.getUserDetails().getUserId()).get(0);
			newRating = ratings.getUserRating5();
		}
	}

	// Getters and Setters
	public Books getCurrentBook() {
		return currentBook;
	}

	public void setCurrentBook(Books currentBook) {
		this.currentBook = currentBook;
	}

	public ShoppingCart getShoppingCart() {
		return shoppingCart;
	}

	public void setShoppingCart(ShoppingCart shoppingCart) {
		this.shoppingCart = shoppingCart;
	}

	public int getCurrentId() {
		return currentId;
	}

	public void setCurrentId(int currentId) {
		this.currentId = currentId;
	}

	public Integer getRating() {
		return rating;

	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

	public Ratings getRatings() {
		return ratings;
	}

	public void setRatings(Ratings ratings) {
		this.ratings = ratings;
	}

	public int getNewRating() {
		return newRating;
	}

	public void setNewRating(int newRating) {
		this.newRating = newRating;
	}

	public int getRatingsCount() {
		return ratingsCount;
	}

	public void setRatingsCount(int ratingsCount) {
		this.ratingsCount = ratingsCount;
	}

	public List<ShoppingCart> getCurrentCart() {
		if (userAccountController.isFlag()){
			currentCart = tempShoppingCartDao.getCart();
		}
		return currentCart;
	}

	public void setCurrentCart(List<ShoppingCart> currentCart) {
		this.currentCart = currentCart;
	}

	public Map<Integer, Integer> getBookNo() {
		bookNumber = new LinkedHashMap<Integer, Integer>();
		for (int i = 1; i <= 10; i++)
			bookNumber.put(i, i); 
		return bookNumber;
	}
}

Online Bookstore Project/src/com/ose/bookstore/controller/HomeController.java
/**
 * 
 */
package com.ose.bookstore.controller;

import java.io.Serializable;
import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.ose.bookstore.model.ejb.BookListDAO;
import com.ose.bookstore.model.entity.Books;


/**
 * Deals with the page links dispatches present in the home page
 * 
 * @author OSE Nepal
 * @version 1.0 18 Sept 2013
 */
@Named
@SessionScoped
public class HomeController implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@EJB
	BookListDAO bookListDao;

	@Inject
	Books books;

	private String searchString;

	private List<Books> bookList;

	private String searchCategory;
	
	@SuppressWarnings("unused")
	private List<Books> filterBookList;
	
	public String goToSearch() {
		System.out.println(searchCategory);
		return "searchedResults";
	}

	// Getters and Setters
	public Books getBooks() {
		return books;
	}

	public void setBooks(Books books) {
		this.books = books;
	}

	public String getSearchString() {
		return searchString;
	}

	public void setSearchString(String searchString) {
		this.searchString = searchString;
	}

	public List<Books> getBookList() {
		return bookListDao.getBookList(); 
	}

	/**Gets bookList according to the search category
	 * @return specified book list
	 */
	public List<Books> getFilterBookList(){
		if (searchCategory.equals("Title")) {
			bookList = bookListDao.search(searchString, "title");
		} else if (searchCategory.equals("Author")) {
			bookList = bookListDao.search(searchString, "author");
		}
		else{
			bookList = bookListDao.search(searchString, "all");
		}
		return bookList;
	}
	
	public void setBookList(List<Books> bookList) {
		this.bookList = getBookList();
	}

	public String getSearchCategory() {
		return searchCategory;
	}

	public void setSearchCategory(String searchCategory) {
		this.searchCategory = searchCategory;
	}

	public void setFilterBookList(List<Books> filterBookList) {
		this.filterBookList = filterBookList;
	}

}

Online Bookstore Project/src/com/ose/bookstore/controller/UserAccountController.java
/**
 * 
 */
package com.ose.bookstore.controller;

import java.io.Serializable;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Map;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import com.ose.bookstore.model.ejb.CountryListDAO;
import com.ose.bookstore.model.ejb.UserAccountDAO;
import com.ose.bookstore.model.entity.UserDetails;


/**
 * Deals with all the page links dispatches present in <b><u>editDetails</u></b> page and the
 * pages involving with <b><u>editDetails</u></b> data
 * @author OSE Nepal
 * @version 1.3.0 Oct 4, 2013
 */
@Named
@SessionScoped
public class UserAccountController implements Serializable {

	private static final long serialVersionUID = 1L;

	@EJB
	UserAccountDAO userAccountDao;

	@EJB
	CountryListDAO countryListDao;

	@Inject
	UserDetails userDetails;

	private boolean flag = false; /*Login status flag; true if logged in*/

	private Map<String, String> countryValue;/*for dropdown menu*/

	@SuppressWarnings("unused")
	private Long memberAge;

	/**
	 * The selected user's detail is edited
	 * 
	 * @return null returns to same page
	 */
	public String editDetails() {
		System.out.println("Current user: " + userDetails.getFirstName());
		userAccountDao.editUser(userDetails);
		FacesContext.getCurrentInstance().addMessage(null,new FacesMessage("Edited Successfully"));
		return "";
	}

	/**
	 * @return forwards to <b><u>orderBooks</u></b> page
	 */
	public String toOrderPage() {
		FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO,"Register/Login Account to buy books", "");
		FacesContext.getCurrentInstance().addMessage(null, message);
		return "registered/orderBooks?faces-redirect=true";
	}

	/**
	 * @return forwards to editDetails page
	 */
	public String showDetails() {
		return "registered/editDetails?faces-redirect=true";
	}

	/**Registers User by persisting in database
	 * @return
	 */
	public String registerUser() {
		Date currentDate = new Date();
		userDetails.setDate(currentDate);
		if(userAccountDao.create(userDetails)){
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Your account has been created"));
			return "/webpages/home?faces-redirect=true";
		}
		else{
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Existing UserEmail"));
			return null;
		}
	}

	/**Sets flag true if correct login info
	 * @return
	 */
	public String checkLogin() {
		FacesContext context = FacesContext.getCurrentInstance();
		
		if (userDetails.getPassword().isEmpty()	|| userDetails.getUserEmail().isEmpty()) {
			context.addMessage(null, new FacesMessage("UserEmail/Password is empty"));
			flag = false;
		}else if (userAccountDao.getCurrentUser(userDetails).isEmpty()) {
			context.addMessage(null, new FacesMessage("Login failed: Email address or Password is incorrect"));
			flag = false;
		} else {
			userDetails = userAccountDao.getCurrentUser(userDetails).get(0);
			// userSession.setUser(userDetails);
			// Cookie loginCookie = new Cookie("user",
			// userDetails.getFirstName());
			// loginCookie.setMaxAge(30*60);
			flag = true;
		}
		
		return null;
	}

	/**
	 * Logs the current user out by invalidating the session.
	 * 
	 * @return page {@literal faces-config.xml} to redirect back to the
	 *         {@literal home.xhtml} page.
	 */
	public String logout() {
		FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
		// Cookie loginCookie = null;
		// loginCookie.setMaxAge(0);
		flag = false;
		return "/webpages/home?faces-redirect=true";
	}

	public String signUp() {
		return "/webpages/userRegistration?faces-redirect=true";
	}

	// Getters and Setters
	public boolean isFlag() {
		return flag;
	}

	public void setFlag(boolean flag) {
		this.flag = flag;
	}

	public UserDetails getUserDetails() {
		return userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	public Map<String, String> getSelectCountryValue() {
		countryValue = new LinkedHashMap<String, String>();
		for (int i = 0; i < countryListDao.getCountry().size(); i++) {
			countryValue.put(countryListDao.getCountry().get(i).getName(),
					countryListDao.getCountry().get(i).getName());
		}
		return countryValue;
	}

	/**Calculates current user's membership age
	 * @return membership age in days
	 */
	public Long getMemberAge() {
		Date currentDate = new Date();
		long diff = currentDate.getTime() - userDetails.getDate().getTime();
		return (diff / (1000 * 60 * 60 * 24));
	}

	public void setMemberAge(Long memberAge) {
		this.memberAge = memberAge;
	}

}

Online Bookstore Project/WebContent/webpages/bookProfile.xhtml
<!DOCTYPE html>

<!-- Page showing details of selected books-->

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<h:head></h:head>
<h:outputStylesheet library="css" name="common.css" />

<!-- Include template containing header and footer -->

<ui:composition template="/WEB-INF/templates/headerFooterTemplate.xhtml">


	<ui:define name="content">

		<!-- Include login template-->
		
		<ui:include src="/WEB-INF/templates/logintemplate.xhtml"></ui:include>
		
		<!--Include navigation template -->
		
		<ui:include src="/WEB-INF/templates/navigation.xhtml"></ui:include>

		<f:view loacle="en">
			<h:body>
				<br />
				
				<!--Required inforamation of books -->
				
				<p:layout fullPage="false">

					<p:layoutUnit position="west"
						header="#{booksController.currentBook.title}" size="260"
						style="border: none;">
						<h:graphicImage library="images"
							name="#{booksController.currentBook.coverPage}" width="220"
							height="220"></h:graphicImage>
						<h:panelGroup></h:panelGroup>
						<p:rating value="#{booksController.rating}" readonly="true">
						</p:rating>
							(#{booksController.ratingsCount} users)
					</p:layoutUnit>
					
					<p:layoutUnit position="center" style="border: none; height: 200px;"
						header="Book Information" size="20" >
						
						<f:metadata>
							<f:viewParam name="id" value="#{booksController.currentId}" />
							<f:event type="preRenderView" listener="#{booksController.init}" />
						</f:metadata>

						<h:panelGrid columns="2">

							<h:outputLabel value="Book Name: " style="color: red;" />
							<h:outputLabel value="#{booksController.currentBook.title}" />

							<h:outputLabel value="Publisher: " style="color: red;" />
							<h:outputLabel value="#{booksController.currentBook.publisher}" />

							<h:outputLabel value="Author:" style="color: red;" />
							<h:outputLabel value="#{booksController.currentBook.author}" />

							<h:outputLabel value="ISBN:" style="color: red;" />
							<h:outputLabel value="#{booksController.currentBook.isbn}" />

							<h:outputLabel value="Edition:" style="color: red;" />
							<h:outputLabel value="#{booksController.currentBook.edition}" />

							<h:outputLabel value="Publication Date:" style="color: red;" />
							<h:outputLabel value="#{booksController.currentBook.pubDate}" />

							<h:outputLabel value="Description: " style="color: red;" />
							<h:outputLabel value="#{booksController.currentBook.description}" />

							<h:outputLabel value="Discount: " style="color: red;" />
							<h:outputLabel value="#{booksController.currentBook.discount}" />

							<h:outputLabel value="Price: " style="color: red;" />
							<h:outputLabel value="#{booksController.currentBook.price}">
								<f:convertNumber currencySymbol="$" type="currency" />
							</h:outputLabel>

							<h:outputLabel value="Rating:" />
							<h:form>
								<p:growl id="rating" severity="info" life="2000"></p:growl>
								<h:panelGroup></h:panelGroup>
								<p:rating cancel="false" value="#{booksController.newRating}" readonly="#{!userAccountController.flag}">
									<p:ajax event="rate" listener="#{booksController.onrate}"
										update="rating"></p:ajax>
								</p:rating>
							</h:form>

						</h:panelGrid>

					</p:layoutUnit>
					<h:form>
						
						<p:layoutUnit position="east" size="250" style="border: none;">
							
							<h:panelGrid columns="3">

								<h:outputLabel value="Quantity" />

								<p:selectOneMenu
									value="#{booksController.shoppingCart.bookQuantity}">
									<f:selectItems value="#{booksController.bookNo}"></f:selectItems>
								</p:selectOneMenu>
								
								<h:inputHidden value="#{booksController.currentBook.bookId}" />
								
								<h:commandButton action="#{booksController.addToShoppingCart}" id = "add"
									value="Add to Cart" >
		
								</h:commandButton>

							</h:panelGrid>


						</p:layoutUnit>
					</h:form>

				</p:layout>

			</h:body>
		</f:view>

	</ui:define>

</ui:composition>
</html>

Online Bookstore Project/WebContent/webpages/browsebooks.xhtml
<!DOCTYPE html>

<!-- Page showing the list of books-->

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">
<h:head></h:head>
<h:outputStylesheet library="css" name="common.css" />

<!-- include header and footer through template -->

<ui:composition template="/WEB-INF/templates/headerFooterTemplate.xhtml">
	<ui:define name="title">Books</ui:define>

	<ui:define name="content">



		<!-- Division of section for userlogin and displaying the logged user -->
		<!-- Include logintemplate-->
		<ui:include src="/WEB-INF/templates/logintemplate.xhtml"></ui:include>

		<!-- include navigation section from template -->


		<ui:include src="/WEB-INF/templates/navigation.xhtml"></ui:include>

		<!-- beginning of the actual body part -->
		<f:view locale="en">
			<h:body>

				<p:growl severity="info"></p:growl>
				<br />


				<h:form>
					<!--Section for search options -->
					
					<p:fieldset legend="Browse Books" style="height: 300px;">
						<h:panelGrid columns="5">
							<h:outputLabel value="Search Category" />
							<p:selectOneMenu value="#{homeController.searchCategory}">
										<f:selectItem itemLabel="All" itemValue = "All" />
										<f:selectItem itemLabel="Author" itemValue="Author" />
										<f:selectItem itemLabel="Title" itemValue="Title" />
									</p:selectOneMenu>

							<h:inputText id="search" styleClass="search"
										value="#{homeController.searchString}" />
								<p:watermark for="search" value="Enter book title or author "></p:watermark>
							<h:commandButton value = "search" action = "#{homeController.goToSearch}"></h:commandButton>
						</h:panelGrid>
						
						<!-- List of books with their thumbnail of images and name-->
						
						<p:dataGrid paginator="true" var="books"
							value="#{homeController.bookList}" rows="6" id="grid"
							rendered="true">

							<p:panel>

								<p:panelGrid columns="1">
									<h:link outcome="bookProfile">
										<f:param name="id" value="#{books.bookId}" />

										<h:graphicImage library="images" name="#{books.coverPage}"
											width="200" height="200" />
									</h:link>

									<h:link value="#{books.title}"
										outcome="bookProfile">
										<f:param name="id" value="#{books.bookId}" />
									</h:link>

								</p:panelGrid>

							</p:panel>

						</p:dataGrid>

					</p:fieldset>
				</h:form>

			</h:body>
		</f:view>

	</ui:define>
</ui:composition>



</html>

Online Bookstore Project/WebContent/webpages/searchedResults.xhtml
<!DOCTYPE html >

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head></h:head>
<ui:composition template="/WEB-INF/templates/headerFooterTemplate.xhtml">

	<ui:define name="content">

		<ui:define name="title">Searched Results</ui:define>
		
		<!--Include login template  -->
		
		<ui:include src="/WEB-INF/templates/logintemplate.xhtml"></ui:include>

		<!-- Include navigation template -->
		<ui:include src="/WEB-INF/templates/navigation.xhtml"></ui:include>
		<h:body>
			<br />
			<h:form>
				<p:fieldset legend="Searched Results" style="height: 300px;">
					<h:panelGrid columns="5">
						<h:outputLabel value="Search Category" />
								<p:selectOneMenu value="#{homeController.searchCategory}">
									<f:selectItem itemLabel="All" itemValue = "All" />
									<f:selectItem itemLabel="Author" itemValue="Author" />
									<f:selectItem itemLabel="Title" itemValue="Title" />
								</p:selectOneMenu>
						<h:inputText id="search" styleClass="search"
							value="#{homeController.searchString}" />
						<p:watermark for="search" value="Enter bookname/author name"></p:watermark>
						<h:commandButton value="search"
							action="#{homeController.goToSearch}"></h:commandButton>
					</h:panelGrid>
					<p:dataGrid paginator="true" var="books"
						value="#{homeController.filterBookList}" rows="6" id="grid"
						rendered="true">

						<p:panel>

							<p:panelGrid columns="1">
								<h:link outcome="bookProfile">
									<f:param name="id" value="#{books.bookId}" />

									<h:graphicImage library="images" name="#{books.coverPage}"
										width="200" height="200" />
								</h:link>

								<h:link value="#{books.title}" outcome="bookProfile">
									<f:param name="id" value="#{books.bookId}" />
								</h:link>

							</p:panelGrid>

						</p:panel>

					</p:dataGrid>


				</p:fieldset>
			</h:form>


		</h:body>


	</ui:define>

</ui:composition>
</html>