Online Bookstore Project/src/com/ose/bookstore/controller/UserAccountController.java
/**
 * 
 */
package com.ose.bookstore.controller;

import java.io.Serializable;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Map;

import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import com.ose.bookstore.model.ejb.CountryListDAO;
import com.ose.bookstore.model.ejb.UserAccountDAO;
import com.ose.bookstore.model.entity.UserDetails;


/**
 * Deals with all the page links dispatches present in <b><u>editDetails</u></b> page and the
 * pages involving with <b><u>editDetails</u></b> data
 * @author OSE Nepal
 * @version 1.3.0 Oct 4, 2013
 */
@Named
@SessionScoped
public class UserAccountController implements Serializable {

	private static final long serialVersionUID = 1L;

	@EJB
	UserAccountDAO userAccountDao;

	@EJB
	CountryListDAO countryListDao;

	@Inject
	UserDetails userDetails;

	private boolean flag = false; /*Login status flag; true if logged in*/

	private Map<String, String> countryValue;/*for dropdown menu*/

	@SuppressWarnings("unused")
	private Long memberAge;

	/**
	 * The selected user's detail is edited
	 * 
	 * @return null returns to same page
	 */
	public String editDetails() {
		System.out.println("Current user: " + userDetails.getFirstName());
		userAccountDao.editUser(userDetails);
		FacesContext.getCurrentInstance().addMessage(null,new FacesMessage("Edited Successfully"));
		return "";
	}

	/**
	 * @return forwards to <b><u>orderBooks</u></b> page
	 */
	public String toOrderPage() {
		FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO,"Register/Login Account to buy books", "");
		FacesContext.getCurrentInstance().addMessage(null, message);
		return "registered/orderBooks?faces-redirect=true";
	}

	/**
	 * @return forwards to editDetails page
	 */
	public String showDetails() {
		return "registered/editDetails?faces-redirect=true";
	}

	/**Registers User by persisting in database
	 * @return
	 */
	public String registerUser() {
		Date currentDate = new Date();
		userDetails.setDate(currentDate);
		if(userAccountDao.create(userDetails)){
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Your account has been created"));
			return "/webpages/home?faces-redirect=true";
		}
		else{
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Existing UserEmail"));
			return null;
		}
	}

	/**Sets flag true if correct login info
	 * @return
	 */
	public String checkLogin() {
		FacesContext context = FacesContext.getCurrentInstance();
		
		if (userDetails.getPassword().isEmpty()	|| userDetails.getUserEmail().isEmpty()) {
			context.addMessage(null, new FacesMessage("UserEmail/Password is empty"));
			flag = false;
		}else if (userAccountDao.getCurrentUser(userDetails).isEmpty()) {
			context.addMessage(null, new FacesMessage("Login failed: Email address or Password is incorrect"));
			flag = false;
		} else {
			userDetails = userAccountDao.getCurrentUser(userDetails).get(0);
			// userSession.setUser(userDetails);
			// Cookie loginCookie = new Cookie("user",
			// userDetails.getFirstName());
			// loginCookie.setMaxAge(30*60);
			flag = true;
		}
		
		return null;
	}

	/**
	 * Logs the current user out by invalidating the session.
	 * 
	 * @return page {@literal faces-config.xml} to redirect back to the
	 *         {@literal home.xhtml} page.
	 */
	public String logout() {
		FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
		// Cookie loginCookie = null;
		// loginCookie.setMaxAge(0);
		flag = false;
		return "/webpages/home?faces-redirect=true";
	}

	public String signUp() {
		return "/webpages/userRegistration?faces-redirect=true";
	}

	// Getters and Setters
	public boolean isFlag() {
		return flag;
	}

	public void setFlag(boolean flag) {
		this.flag = flag;
	}

	public UserDetails getUserDetails() {
		return userDetails;
	}

	public void setUserDetails(UserDetails userDetails) {
		this.userDetails = userDetails;
	}

	public Map<String, String> getSelectCountryValue() {
		countryValue = new LinkedHashMap<String, String>();
		for (int i = 0; i < countryListDao.getCountry().size(); i++) {
			countryValue.put(countryListDao.getCountry().get(i).getName(),
					countryListDao.getCountry().get(i).getName());
		}
		return countryValue;
	}

	/**Calculates current user's membership age
	 * @return membership age in days
	 */
	public Long getMemberAge() {
		Date currentDate = new Date();
		long diff = currentDate.getTime() - userDetails.getDate().getTime();
		return (diff / (1000 * 60 * 60 * 24));
	}

	public void setMemberAge(Long memberAge) {
		this.memberAge = memberAge;
	}

}

Online Bookstore Project/WebContent/webpages/registered/creditCard.xhtml
<!DOCTYPE html>


<!-- Page showing the credit card and asking user the information on credit card-->

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<!-- Include header footer tempalte-->

<ui:composition template="/WEB-INF/templates/headerFooterTemplate.xhtml">

	<ui:define name="title">Credit Card</ui:define>

	<ui:define name="content">
	
		<f:view locale="en">

			<h:body>
				
				<h:form style="margin-left: 450px; margin-top: 0px;">
				
					<h:panelGrid columns="4" styleClass="creditCardTable">
						<h:graphicImage library="images" name="credit_card_image.gif" style=""></h:graphicImage>
						
						<h:outputLabel value="Card Type:" />
						
						<p:selectOneMenu id="cardTypeId">
							<f:selectItem itemLabel="Visa" itemValue="Visa" />
							<f:selectItem itemLabel="American Express"
								itemValue="American Express" />
							<f:selectItem itemLabel="Master Card" itemValue="Master Card" />
						</p:selectOneMenu>
						<h:panelGroup></h:panelGroup>
						<h:panelGroup></h:panelGroup>
						
						<h:outputLabel value="Card Number:" />
						<p:inputText/>
						<h:panelGroup></h:panelGroup>
						<h:panelGroup></h:panelGroup>
						
						<h:outputLabel value="Card Holder Full Name:" />
						<p:inputText id="creditCardFullName"
							required="true" />
						<h:panelGroup></h:panelGroup>
						<h:panelGroup></h:panelGroup>
					
						
						<h:outputLabel
							value="Expiry Date:&#160;" />	
						<p:selectOneMenu>
							<f:selectItem itemLabel="1" itemValue="1"></f:selectItem>
							<f:selectItem itemLabel="2" itemValue="2"></f:selectItem>
							<f:selectItem itemLabel="3" itemValue="3"></f:selectItem>
							<f:selectItem itemLabel="4" itemValue="4"></f:selectItem>
							<f:selectItem itemLabel="5" itemValue="5"></f:selectItem>
							<f:selectItem itemLabel="6" itemValue="6"></f:selectItem>
							<f:selectItem itemLabel="7" itemValue="7"></f:selectItem>
							<f:selectItem itemLabel="8" itemValue="8"></f:selectItem>
							<f:selectItem itemLabel="9" itemValue="9"></f:selectItem>
							<f:selectItem itemLabel="10" itemValue="10"></f:selectItem>
							<f:selectItem itemLabel="11" itemValue="11"></f:selectItem>
							<f:selectItem itemLabel="12" itemValue="12"></f:selectItem>
						</p:selectOneMenu>
						<p:selectOneMenu>
							<f:selectItem itemLabel="2013" itemValue="2013"></f:selectItem>
							<f:selectItem itemLabel="2014" itemValue="2014"></f:selectItem>
							<f:selectItem itemLabel="2015" itemValue="2015"></f:selectItem>
							<f:selectItem itemLabel="2016" itemValue="2016"></f:selectItem>
						</p:selectOneMenu>
						<h:panelGroup></h:panelGroup>

						<h:commandButton value="Confirm" action="thanks.xhtml"></h:commandButton>
					</h:panelGrid>
				</h:form>
			</h:body>

		</f:view>

		<h:form>

		</h:form>


	</ui:define>

</ui:composition>
</html>

Online Bookstore Project/WebContent/webpages/registered/editDetails.xhtml
<!DOCTYPE html>

<!-- Page to edit details of registered user-->

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<!-- Include header footer template-->

<ui:composition template="/WEB-INF/templates/headerFooterTemplate.xhtml">

	<ui:define name="title">My Account</ui:define>
	
	<ui:define name="content">
	
		<!-- Include login template-->
		
		<ui:include src="/WEB-INF/templates/logintemplate.xhtml"></ui:include>
		
		<!-- Include navigation template -->
		
		<ui:include src="/WEB-INF/templates/navigation.xhtml"></ui:include>

		<f:view locale="en">
			<h:body>
			<p:layout fullPage="false">
				<p:layoutUnit position="center" header="Edit Details" rendered="true">
				
				<p:growl severity="info"></p:growl>
				<h:form styleClass="signUpForm" id="signUpId">
				
					<!-- Display all the error messages -->
					<p:message showDetail="true" for = "firstName"></p:message>
					<p:message showDetail= "true" for = "middleName"></p:message>
					<p:message showDetail="true" for = "lastName"></p:message>
					<p:message showDetail="true" for = "country"></p:message>
					<p:message showDetail="true" for = "phone"></p:message>
					<p:message showDetail="true" for = "city"></p:message>
					<p:message showDetail="true" for = "state"></p:message>
					<p:message showDetail="true" for = "streetName"></p:message>
					<p:message showDetail="true" for = "zipCode"></p:message>
					
					
					<!--Display all the entered information of selected registered user and  allow them to edit-->
					
					<h:panelGrid styleClass="signUpPanelGrid" id="signUpPanelId"
						columns="4">
						<h:outputLabel style="color: red;"
							value="The field with * mark are mandatory" />
						<h:panelGroup></h:panelGroup>
						<h:panelGroup></h:panelGroup>
						<h:panelGroup></h:panelGroup>

						<h:panelGroup></h:panelGroup>
						<h:outputLabel value="First Name*" />
						<h:outputLabel value="Middle Name" />
						<h:outputLabel value="Last Name*" />

						<h:outputLabel value="Full Name*" />
						
						<p:inputText id = "firstName"
							value="#{userAccountController.userDetails.firstName}"
							required="true" requiredMessage="First Name cannot  be empty"
							validatorMessage="Enter the Alphabets only in First Name">
							<f:validateRegex pattern="[a-zA-Z]*" />
							<f:validateLength minimum="2" maximum="30" />
						</p:inputText>

						<p:inputText id = "middleName"
							value="#{userAccountController.userDetails.middleName}">
						</p:inputText>
							
						<p:inputText id = "lastName" value="#{userAccountController.userDetails.lastName}"
							required="true" requiredMessage="Last Name cannot be empty" validatorMessage="Enter Only in Last Name">
							<f:validateRegex pattern="[a-zA-Z]*" />
							<f:validateLength minimum="2" maxium="30" />
						</p:inputText>

						<h:outputLabel value="Enter Email*" />
						<h:outputText value="#{userAccountController.userDetails.userEmail}"></h:outputText>
						<h:panelGroup></h:panelGroup>
						<h:panelGroup></h:panelGroup>

						<h:outputLabel value="Select Country*" />
						<p:selectOneMenu id = "country" value="#{userAccountController.userDetails.country}" rendered="true" requiredMessage="Slect the country">
							<f:selectItems
								value="#{userAccountController.selectCountryValue}"></f:selectItems>
						</p:selectOneMenu>
						<h:panelGroup></h:panelGroup>
						<h:panelGroup></h:panelGroup>

						<p:outputLabel id = "phone" value="Phone" />
						<p:inputMask mask="9999-999-999"
							value="#{userAccountController.userDetails.phone}"></p:inputMask>

						<h:panelGroup></h:panelGroup>
						<h:panelGroup></h:panelGroup>

						<h:outputLabel  value="State*" />
						<p:inputText id ="state" value="#{userAccountController.userDetails.state}" required="true" requiredMessage="Enter State" />
						<h:panelGroup></h:panelGroup>
						<h:panelGroup></h:panelGroup>

						<p:outputLabel  value="City*" />
						<p:inputText id = "city" value="#{userAccountController.userDetails.city}"
							required="true" requiredMessage="Enter City" />

						<h:panelGroup></h:panelGroup>
						<h:panelGroup></h:panelGroup>

						<h:outputLabel  value="Street Name*" />
						<p:inputText id = "streetName" value="#{userAccountController.userDetails.streetName}" required="true" requiredMessage="Enter Street Name" />
						<h:panelGroup></h:panelGroup>
						<h:panelGroup></h:panelGroup>

						<h:outputLabel  value="Street Number" />
						<p:inputText id = "streetNumber" value="#{userAccountController.userDetails.streetNo}" />
						<h:panelGroup></h:panelGroup>
						<h:panelGroup></h:panelGroup>
						
						<p:outputLabel  value="Building Number" />
						<p:inputText id = "buildingNumber"
							value="#{userAccountController.userDetails.buildingNo}" />
						<h:panelGroup></h:panelGroup>
						<h:panelGroup></h:panelGroup>

						<p:outputLabel value ="Zip Code*" />
						<p:inputText  id = "zipCode"  value="#{userAccountController.userDetails.zip}"
							required="true" requiredMessage = "Enter Zip Code" />

						<h:panelGroup></h:panelGroup>
						<h:panelGroup></h:panelGroup>

						<h:panelGroup></h:panelGroup>
						
						<h:commandButton value="Edit" action="#{userAccountController.editDetails}"></h:commandButton>

					</h:panelGrid>
					
				</h:form>
	
				</p:layoutUnit>
			</p:layout>
			</h:body>
		</f:view>

	</ui:define>	

</ui:composition>
</html>

Online Bookstore Project/WebContent/webpages/registered/orderBooks.xhtml
<!DOCTYPE html>

<!-- Page taking information for ordering books-->

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">
	
<!-- Include css file-->

<h:head>
	<h:outputStylesheet library="css" name="common.css" />
</h:head>
<!--Include non clickable header template -->

<ui:composition template="/WEB-INF/templates/nonClickableHeaderFooterTemplate.xhtml">

	<ui:define name="title">Order</ui:define>
	
	<ui:define name="content">
		<f:view locale="en">
			<h:body>
				<p:growl severity="info"></p:growl>
				
				<br />
				
				<!-- Show the ordered items along with price including taxes and options for shipping type-->
				
				<p:layout fullPage="false">

					<p:layoutUnit position="center">

						<h:dataTable value="#{shoppingCartController.cartList}" var="cart"
							cellspacing="2" cellpadding="6">
							<h:column>
								<h:graphicImage library="images" name="#{cart.coverPage}"
									width="50" height="50"></h:graphicImage>
							</h:column>
							<h:column>
								<f:facet name="header">Book Name</f:facet>

								<h:outputText value="#{cart.title}" />
							</h:column>
							<h:column>
								<f:facet name="header">Author</f:facet>
								<h:outputText value="#{cart.author}" />
							</h:column>

							<h:column>
								<f:facet name="header">Edition</f:facet>
								<h:outputText value="#{cart.edition}" />
							</h:column>

							<h:column>
								<f:facet name="header">Quantity</f:facet>
								<h:outputText value="#{cart.quantity}" />
							</h:column>

							<h:column>
								<f:facet name="header">Price</f:facet>
								<h:outputText value="#{cart.price}">
									<f:convertNumber currencySymbol="$" type="currency" />
								</h:outputText>
							</h:column>

							<h:column>
								<f:facet name="header">Discount</f:facet>
								<h:outputText value="#{cart.discount}" />
							</h:column>

							<h:column>
								<f:facet name="header">Total Price</f:facet>
								<h:outputText value="#{cart.totalPrice}">
									<f:convertNumber currencySymbol="$" type="currency" />
								</h:outputText>
							</h:column>

						</h:dataTable>
						
						<h:panelGrid columns="3">
							<div id="totalPriceId" style="color: #cc44cc; margin-left: 650px;">Total
								Price:</div>
							<h:outputText value="#{shoppingCartController.tp}" rendered="true"
								style="color: blue;" ><f:convertNumber currencySymbol="$" type="currency"/>
								</h:outputText>
						</h:panelGrid>

						<h:form>
							<!-- Display error message-->
							<h:message for="shippingType" style="color: red;"></h:message>
							
							<h:panelGrid columns="2">

								<h:outputLabel value="Shipping Type:" />

								<p:selectOneRadio id="shippingType"
									value="#{shoppingCartController.shippingType}">
									<f:selectItem itemLabel="Standard (5 days delivery)"
										itemValue="Standard"></f:selectItem>
									<f:selectItem
										itemLabel="Express (2 days delivery, 30 % higher than Standard)"
										itemValue="Express"></f:selectItem>
									<p:ajax event="click" render="shippingCost" update="sum"></p:ajax>
								</p:selectOneRadio>

								<h:outputLabel value="Tax" style="color: green;" />
								<h:outputLabel value="3.5%" style="color: black;" />

								<h:outputLabel value="Total Price(including Shipping and taxes):"
									style="color: #cc44cc;" />
								<h:outputText id="sum"
									value="#{shoppingCartController.totalWithShipping}"
									rendered="true" style="color: blue;"><f:convertNumber currencySymbol="$" type="currency"/>
									</h:outputText>
							</h:panelGrid>


							<p:fieldset legend="Mailing Address">

								<!-- Display all the error messages -->
								<p:message showDetail="true" for = "firstName"></p:message>
								<p:message showDetail= "true" for = "middleName"></p:message>
								<p:message showDetail="true" for = "lastName"></p:message>
								<p:message showDetail="true" for = "country"></p:message>
								<p:message showDetail="true" for = "phone"></p:message>
								<p:message showDetail="true" for = "city"></p:message>
								<p:message showDetail="true" for = "state"></p:message>
								<p:message showDetail="true" for = "streetName"></p:message>
								<p:message showDetail="true" for = "buildingNumber"></p:message>
								<p:message showDetail="true" for = "streetNumber"></p:message>
								<p:message showDetail="true" for = "zipCode"></p:message>
								
								
								<!-- Input all the required information for signup -->
								
								<h:panelGrid styleClass="signUpPanelGrid" id="signUpPanelId"
									columns="4">
									<h:outputLabel style="color: red;"
										value="The field with * mark are mandatory" />
									<h:panelGroup></h:panelGroup>
									<h:panelGroup></h:panelGroup>
									<h:panelGroup></h:panelGroup>
			
									<h:panelGroup></h:panelGroup>
									<h:outputLabel value="First Name*" />
									<h:outputLabel value="Middle Name" />
									<h:outputLabel value="Last Name*" />
			
									<h:outputLabel value="Full Name*" />
									
									<p:inputText id = "firstName"
										value="#{userAccountController.userDetails.firstName}"
										required="true" requiredMessage="First Name cannot  be empty"
										validatorMessage="Enter the Alphabets only in First Name">
										<f:validateRegex pattern="[a-zA-Z]*" />
										<f:validateLength minimum="2" maximum="30" />
									</p:inputText>
			
									<p:inputText id = "middleName"
										value="#{userAccountController.userDetails.middleName}">
									</p:inputText>
										
									<p:inputText id = "lastName" value="#{userAccountController.userDetails.lastName}"
										required="true" requiredMessage="Last Name cannot be empty" validatorMessage="Enter Only in Last Name">
										<f:validateRegex pattern="[a-zA-Z]*" />
										<f:validateLength minimum="2" maxium="30" />
									</p:inputText>
			
									<h:outputLabel value="Enter Email*" />
									<h:outputText value="#{userAccountController.userDetails.userEmail}"></h:outputText>
									<h:panelGroup></h:panelGroup>
									<h:panelGroup></h:panelGroup>
			
									<h:outputLabel value="Select Country*" />
									<p:selectOneMenu id = "country" value="#{userAccountController.userDetails.country}" rendered="true" requiredMessage="Slect the country">
										<f:selectItems
											value="#{userAccountController.selectCountryValue}"></f:selectItems>
									</p:selectOneMenu>
									<h:panelGroup></h:panelGroup>
									<h:panelGroup></h:panelGroup>
			
									<p:outputLabel id = "phone" value="Phone" />
									<p:inputMask mask="9999-999-999"
										value="#{userAccountController.userDetails.phone}"></p:inputMask>
			
									<h:panelGroup></h:panelGroup>
									<h:panelGroup></h:panelGroup>
			
									<h:outputLabel  value="State*" />
									<p:inputText id ="state" value="#{userAccountController.userDetails.state}" required="true" requiredMessage="Enter State" />
									<h:panelGroup></h:panelGroup>
									<h:panelGroup></h:panelGroup>
			
									<p:outputLabel  value="City*" />
									<p:inputText id = "city" value="#{userAccountController.userDetails.city}"
										required="true" requiredMessage="Enter City" />
			
									<h:panelGroup></h:panelGroup>
									<h:panelGroup></h:panelGroup>
			
									<h:outputLabel  value="Street Name*" />
									<p:inputText id = "streetName" value="#{userAccountController.userDetails.streetName}" required="true" requiredMessage="Enter Street Name" />
									<h:panelGroup></h:panelGroup>
									<h:panelGroup></h:panelGroup>
			
									<h:outputLabel  value="Street Number" />
									<p:inputText id = "streetNumber" value="#{userAccountController.userDetails.streetNo}" />
									<h:panelGroup></h:panelGroup>
									<h:panelGroup></h:panelGroup>
									
									<p:outputLabel  value="Building Number" />
									<p:inputText id = "buildingNumber"
										value="#{userAccountController.userDetails.buildingNo}" />
									<h:panelGroup></h:panelGroup>
									<h:panelGroup></h:panelGroup>
			
									<p:outputLabel value ="Zip Code*" />
									<p:inputText  id = "zipCode"  value="#{userAccountController.userDetails.zip}"
										required="true" requiredMessage = "Enter Zip Code" />
			
									<h:panelGroup></h:panelGroup>
									<h:panelGroup></h:panelGroup>
			
									
										<h:inputHidden id="id"
												value="#{userAccountController.userDetails.userId}">
										</h:inputHidden>
										
									<h:commandButton value="Confirm" action="#{orderController.action(userAccountController.userDetails,shoppingCartController.shippingType,shoppingCartController.cartList)}"></h:commandButton>
			
								</h:panelGrid>

							</p:fieldset>

						</h:form>
					</p:layoutUnit>

				</p:layout>

			</h:body>
		</f:view>

	</ui:define>

</ui:composition>
</html>

Online Bookstore Project/WebContent/webpages/registered/thanks.xhtml
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<ui:composition template="/WEB-INF/templates/headerFooterTemplate.xhtml">

	<ui:define name="title">Thank you</ui:define>	
	<ui:define name="content">
	   <f:view locale = "en">
	   
	   		<h:body>
	   			<b>Thank You for visiting BookStore and ordering books</b>
	   			<div>
	   				<h:outputLink value="${facesContext.externalContext.requestContextPath}/faces/webpages/home.xhtml">Click here to return to home page.</h:outputLink>
	   			</div>
	   		
	   		</h:body>
	   
	   </f:view>
	</ui:define>

</ui:composition>
</html>